### ISSUE TITLE
netbox 2.8

### ISSUE THREAD

**Issue by i4networks** [robustgarlic/netbox-interface-importer#1]
hi,

Is this importer compatible with Netbox 2.8?
netbox-netprod-importer is broken at this moment due to the change of
_choices to OPTIONS in the API

Love to hear from you.

**Comment by robustgarlic** [comment]
Hello,

This has been tested with Netbox 2.8.6.

Thanks,

**Comment by robustgarlic** [comment]
> hi,
> 
> Is this importer compatible with Netbox 2.8?
> netbox-netprod-importer is broken at this moment due to the change of
> _choices to OPTIONS in the API
> 
> Love to hear from you.

I added the netbox version tested on in the readme.

thank you.

**Comment by i4networks** [comment]
i have a 2.8.2 running at this moment.. i will test it and report back.

**Comment by i4networks** [comment]
2.8.2 is also working. 


Thnx for the project.
